"""add missing fields to professional profile

Revision ID: 7bf2c93cb049
Revises: f281535157ab
Create Date: 2026-01-30 14:50:02.969553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf2c93cb049'
down_revision: Union[str, Sequence[str], None] = 'f281535157ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('subtitle', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('subtopic', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('level', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('long_description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('target_audience', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('learning_goals', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('status', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('courses', 'is_published')
    op.drop_column('courses', 'price')
    op.drop_column('courses', 'content_url')
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'content_type')
    op.drop_column('courses', 'lastupdated')
    op.drop_column('courses', 'tags')
    op.drop_column('courses', 'rating_count')
    op.drop_column('courses', 'rating_avg')
    op.add_column('orders', sa.Column('offer_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'orders', 'course_offers', ['offer_id'], ['id'])
    op.add_column('professional_profiles', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.add_column('professional_profiles', sa.Column('verification_status', sa.String(), nullable=True))
    op.alter_column('professional_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('professional_profiles', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('professional_profiles', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('professional_profiles', 'formation_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('professional_profiles', 'specialties',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('professional_profiles', 'professional_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('professional_profiles', 'credentials',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('professional_profiles', 'collegiated')
    op.drop_column('professional_profiles', 'accept_terms')
    op.drop_column('professional_profiles', 'role_other')
    op.drop_column('professional_profiles', 'accept_responsible_use')
    op.drop_column('professional_profiles', 'collegiate_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('collegiate_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('accept_responsible_use', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('role_other', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('accept_terms', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('collegiated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('professional_profiles', 'credentials',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('professional_profiles', 'professional_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('professional_profiles', 'specialties',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('professional_profiles', 'formation_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('professional_profiles', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('professional_profiles', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('professional_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('professional_profiles', 'verification_status')
    op.drop_column('professional_profiles', 'is_complete')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'offer_id')
    op.add_column('courses', sa.Column('rating_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('lastupdated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('content_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'updated_at')
    op.drop_column('courses', 'status')
    op.drop_column('courses', 'requirements')
    op.drop_column('courses', 'learning_goals')
    op.drop_column('courses', 'target_audience')
    op.drop_column('courses', 'long_description')
    op.drop_column('courses', 'short_description')
    op.drop_column('courses', 'level')
    op.drop_column('courses', 'subtopic')
    op.drop_column('courses', 'topic')
    op.drop_column('courses', 'subtitle')
    # ### end Alembic commands ###
