"""add_missing_course_fields

Revision ID: 7c15d43436de
Revises: 29e1b92ec3d3
Create Date: 2026-03-15 16:23:20.864677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c15d43436de'
down_revision: Union[str, Sequence[str], None] = '29e1b92ec3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('directed_to', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('modalities', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'modalities')
    op.drop_column('courses', 'directed_to')
    # ### end Alembic commands ###
