"""add consent and accreditation fields

Revision ID: 954aa8b44982
Revises: 7bf2c93cb049
Create Date: 2026-01-30 15:45:09.118087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954aa8b44982'
down_revision: Union[str, Sequence[str], None] = '7bf2c93cb049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('is_accredited', sa.Boolean(), nullable=True))
    op.add_column('professional_profiles', sa.Column('accept_terms', sa.Boolean(), nullable=True))
    op.add_column('professional_profiles', sa.Column('accept_responsible_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_profiles', 'accept_responsible_use')
    op.drop_column('professional_profiles', 'accept_terms')
    op.drop_column('professional_profiles', 'is_accredited')
    # ### end Alembic commands ###
