"""add_banner_url_to_courses

Revision ID: e995715b6344
Revises: 954aa8b44982
Create Date: 2026-03-10 23:37:25.808249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e995715b6344'
down_revision: Union[str, Sequence[str], None] = '954aa8b44982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'banner_url')
    # ### end Alembic commands ###
