"""create_professional_profile_table

Revision ID: f281535157ab
Revises: 779b5a8b51c2
Create Date: 2026-01-21 18:00:05.494870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f281535157ab'
down_revision: Union[str, Sequence[str], None] = '779b5a8b51c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('role_other', sa.String(), nullable=True),
    sa.Column('formation_level', sa.String(), nullable=False),
    sa.Column('specialty', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('professional_status', sa.String(), nullable=False),
    sa.Column('collegiated', sa.Boolean(), nullable=True),
    sa.Column('collegiate_number', sa.String(), nullable=True),
    sa.Column('accept_terms', sa.Boolean(), nullable=True),
    sa.Column('accept_responsible_use', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='orderstatus'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('buyer', 'seller', 'admin', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('buyer', 'seller', 'admin', name='userrole'),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='orderstatus'),
               nullable=True)
    op.drop_table('professional_profiles')
    # ### end Alembic commands ###
